# Generated by Django 5.2.14 on 2026-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_limite', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('whatsapp', models.CharField(help_text='Ex: 5534999998888', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
